# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Generic CI/CD Pipeline (.NET Library)
on:
  push:
    branches: [main]
    paths-ignore:
      - .codecov
      - .docfx
      - .github
      - .nuget
  pull_request:
    branches: [main]
env:
  DOTNET_NOLOGO: true
  VERSION: '1.1.${{ github.run_number }}'
  PACKAGES_URL: https://nuget.pkg.github.com
    
jobs:
  build:
    name: 🛠️ Build
    runs-on: ubuntu-latest

    permissions:
      packages:write
      contents:read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build package
        run: dotnet pack -p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }} -p:PackageVersion=${{ env.VERSION }} --output .
      
      - name: Publish package
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.PACKAGES_URL }}/${{ github.repository_owner }}/index.json
       
      - run: gh api repos/${{ github.repository_owner }}/nuget-install/dispatches <<< '{"event_type":"build"}' --input -
        if: ${{ env.REPO_TOKEN != null }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
